export enum FormeMedicament {
  COMPRIME = 'COMPRIME',
  GELULE = 'GELULE',
  SIROP = 'SIROP',
  SOLUTION_INJECTABLE = 'SOLUTION_INJECTABLE',
  POMMADE = 'POMMADE',
  CREME = 'CREME',
  SUPPOSITOIRE = 'SUPPOSITOIRE',
  GOUTTES = 'GOUTTES',
  SPRAY = 'SPRAY',
  POUDRE = 'POUDRE',
  AUTRE = 'AUTRE'
}